// Versão atual da app — mostrada no fundo do menu lateral.
// Atualizar este número sempre que se gera um novo zip de entrega.
// Convenção do nome do ficheiro entregue: HBW-v<APP_VERSION>.zip (ex.: HBW-v1.2.zip)
const APP_VERSION = '1.4';

const STR = {
  pt: {
    firstLogTitle: 'Primeiro registo do dia',
    firstLogLabel: 'Valor atual do contador (metros)',
    firstLogBtn: 'Registar e começar turno',
    shiftLabel: 'Turno',
    startedAt: 'início às',
    weekLabel: 'Semana',
    shiftOver: 'turno terminado',
    totalToday: 'Total hoje',
    avgRate: 'Média m/hora',
    forecastLabel: 'Previsão até ao fim do turno',
    predictedNowLabel: 'Previsão para agora',
    newLogLabel: 'Novo registo (valor total acumulado)',
    registerBtn: 'Registar',
    pausaOff: 'Marcar pausa de 30 min',
    pausaOn: '☕ Pausa registada (−30 min)',
    historyLabel: 'Histórico de hoje',
    noRecords: 'Sem registos',
    endShiftBtn: 'Terminar turno',
    confirmEndShift: 'Terminar o turno de hoje? Os registos ficam guardados e o dia passa a contar como fechado (aparece nos Recordes e Resumos a partir de agora).',
    shiftClosedBadge: 'turno fechado',
    reopenShift: 'Reabrir turno',
    confirmReopen: 'Reabrir o turno de hoje? Volta a poder registar novos valores.',
    editSchedule: 'Ajustar horário deste turno',
    promptStart: 'Hora de início',
    promptEnd: 'Hora de fim',
    invalidTime: 'Horário inválido',
    footerNote: 'Nota: a notificação fixa funciona melhor com a app aberta ou em segundo plano recente. Se o telemóvel poupar bateria de forma agressiva, abra a app de vez em quando para a notificação atualizar.',
    enableNotif: 'Ativar notificações',
    enableNotifBanner: 'Ative as notificações para ver o total, a média e a previsão fixos na barra de notificações.',
    invalidValue: 'Introduza um valor válido',
    logged: 'Registado',
    notifEnabled: 'Notificações ativadas',
    reminderBody: 'Hora de registar o valor de metros!',
    menuLang: 'Idioma',
    splashToggleLabel: 'Animação inicial',
    menuHistory: 'Dias anteriores',
    menuRecords: 'Recordes',
    menuNotes: 'Notas',
    newNote: '+ Nova nota',
    notePlaceholder: 'Escreva aqui...',
    addPhoto: '+ Foto',
    saveNote: 'Guardar',
    deleteNote: 'Apagar nota',
    confirmDeleteNote: 'Apagar esta nota?',
    emptyNote: 'A nota está vazia',
    noNotes: 'Ainda sem notas',
    storageFull: 'Sem espaço de armazenamento — experimente remover fotos ou notas antigas',
    photosCount: 'fotos',
    menuBack: '← Voltar',
    recordTotal: 'Recorde de produção diária',
    recordRate: 'Melhor média m/hora',
    noHistory: 'Ainda sem dias anteriores',
    noRecordsYet: 'Ainda sem dados suficientes',
    dayDetailTotal: 'Total',
    dayDetailAvg: 'Média m/h',
    dayDetailTurno: 'Turno',
    editPrompt: 'Novo valor (metros):',
    confirmDeleteLog: 'Apagar este registo?',
    quickNoteLabel: 'Nova nota',
    quickNotePlaceholder: 'ex: paragem na linha 2, madeira húmida...',
    addNoteBtn: 'Adicionar nota',
    editNotePrompt: 'Editar nota:',
    editNoteTimePrompt: 'Hora da nota:',
    confirmDeleteNoteEntry: 'Apagar esta nota?',
    cancelBtn: 'Cancelar',
    hoursLabel: 'Horas efetivas',
    pausaSince: 'desde',
    menuNotif: 'Notificações',
    notifToggleLabel: 'Notificação fixa do turno ativa',
    notifHelpText: 'Mostra o total, a média e a previsão numa notificação fixa enquanto o turno está aberto. Se recusou a permissão por engano, ative manualmente em: Chrome → ⋮ → Definições do site → Notificações.',
    lowerValueConfirm: 'O valor é menor que o último registo ({v} m). Continuar mesmo assim?',
    menuSummary: 'Resumos',
    tabWeek: 'Semana',
    tabMonth: 'Mês',
    summaryTotal: 'Total do período',
    summaryAvg: 'Média m/hora',
    summaryNoData: 'Sem dados neste período',
    previousPeriods: 'Períodos anteriores',
    legendGoalMet: 'Meta atingida',
    legendBelowGoal: 'Abaixo da meta',
    legendLow: 'Fraca produção',
    menuData: 'Dados',
    exportBtn: 'Exportar dados (cópia de segurança)',
    exportCsvBtn: 'Exportar CSV (Excel)',
    importBtn: 'Importar dados',
    importWarning: 'Isto substitui os dados atuais pelos do ficheiro escolhido. Continuar?',
    importSuccess: 'Dados importados com sucesso',
    importError: 'Ficheiro inválido',
    dataExplain: 'Guarde uma cópia de segurança de vez em quando (ex: no Google Drive). Se limpar os dados do site ou trocar de telemóvel, é a única forma de recuperar o histórico e as notas.'
  },
  de: {
    firstLogTitle: 'Erste Erfassung des Tages',
    firstLogLabel: 'Aktueller Zählerstand (Meter)',
    firstLogBtn: 'Erfassen und Schicht starten',
    shiftLabel: 'Schicht',
    startedAt: 'Start um',
    weekLabel: 'Woche',
    shiftOver: 'Schicht beendet',
    totalToday: 'Gesamt heute',
    avgRate: 'Ø Meter/Stunde',
    forecastLabel: 'Prognose bis Schichtende',
    predictedNowLabel: 'Prognose für jetzt',
    newLogLabel: 'Neue Erfassung (Gesamtstand)',
    registerBtn: 'Erfassen',
    pausaOff: '30 Min. Pause markieren',
    pausaOn: '☕ Pause erfasst (−30 Min.)',
    historyLabel: 'Verlauf heute',
    noRecords: 'Keine Einträge',
    endShiftBtn: 'Schicht beenden',
    confirmEndShift: 'Die heutige Schicht beenden? Die Einträge bleiben erhalten und der Tag zählt ab jetzt als abgeschlossen (erscheint in Rekorden und Übersicht).',
    shiftClosedBadge: 'Schicht beendet',
    reopenShift: 'Schicht wieder öffnen',
    confirmReopen: 'Die heutige Schicht wieder öffnen? Neue Werte können wieder erfasst werden.',
    editSchedule: 'Schichtzeiten dieses Tages anpassen',
    promptStart: 'Startzeit',
    promptEnd: 'Endzeit',
    invalidTime: 'Ungültige Zeit',
    footerNote: 'Hinweis: Die feste Benachrichtigung funktioniert am zuverlässigsten, wenn die App geöffnet ist oder kürzlich im Hintergrund lief. Bei aggressivem Akkusparen bitte die App gelegentlich öffnen, damit die Benachrichtigung aktualisiert wird.',
    enableNotif: 'Benachrichtigungen aktivieren',
    enableNotifBanner: 'Aktivieren Sie Benachrichtigungen, um Gesamt, Ø und Prognose fest in der Benachrichtigungsleiste zu sehen.',
    invalidValue: 'Bitte einen gültigen Wert eingeben',
    logged: 'Erfasst',
    notifEnabled: 'Benachrichtigungen aktiviert',
    reminderBody: 'Zeit, den Meterstand zu erfassen!',
    menuLang: 'Sprache',
    splashToggleLabel: 'Start-Animation',
    menuHistory: 'Vorherige Tage',
    menuRecords: 'Rekorde',
    menuNotes: 'Notizen',
    newNote: '+ Neue Notiz',
    notePlaceholder: 'Hier schreiben...',
    addPhoto: '+ Foto',
    saveNote: 'Speichern',
    deleteNote: 'Notiz löschen',
    confirmDeleteNote: 'Diese Notiz löschen?',
    emptyNote: 'Die Notiz ist leer',
    noNotes: 'Noch keine Notizen',
    storageFull: 'Kein Speicherplatz mehr — alte Fotos oder Notizen entfernen',
    photosCount: 'Fotos',
    menuBack: '← Zurück',
    recordTotal: 'Tagesproduktionsrekord',
    recordRate: 'Beste Ø Meter/Stunde',
    noHistory: 'Noch keine vorherigen Tage',
    noRecordsYet: 'Noch nicht genug Daten',
    dayDetailTotal: 'Gesamt',
    dayDetailAvg: 'Ø m/h',
    dayDetailTurno: 'Schicht',
    editPrompt: 'Neuer Wert (Meter):',
    confirmDeleteLog: 'Diesen Eintrag löschen?',
    quickNoteLabel: 'Neue Notiz',
    quickNotePlaceholder: 'z.B. Stillstand an Linie 2, feuchtes Holz...',
    addNoteBtn: 'Notiz hinzufügen',
    editNotePrompt: 'Notiz bearbeiten:',
    editNoteTimePrompt: 'Uhrzeit der Notiz:',
    confirmDeleteNoteEntry: 'Diese Notiz löschen?',
    cancelBtn: 'Abbrechen',
    hoursLabel: 'Effektive Stunden',
    pausaSince: 'seit',
    menuNotif: 'Benachrichtigungen',
    notifToggleLabel: 'Feste Schicht-Benachrichtigung aktiv',
    notifHelpText: 'Zeigt Gesamt, Ø und Prognose fest in einer Benachrichtigung, solange die Schicht offen ist. Falls Sie die Berechtigung versehentlich abgelehnt haben: Chrome → ⋮ → Website-Einstellungen → Benachrichtigungen.',
    lowerValueConfirm: 'Der Wert ist niedriger als der letzte Eintrag ({v} m). Trotzdem fortfahren?',
    menuSummary: 'Übersicht',
    tabWeek: 'Woche',
    tabMonth: 'Monat',
    summaryTotal: 'Gesamt im Zeitraum',
    summaryAvg: 'Ø Meter/Stunde',
    summaryNoData: 'Keine Daten in diesem Zeitraum',
    previousPeriods: 'Vorherige Zeiträume',
    legendGoalMet: 'Ziel erreicht',
    legendBelowGoal: 'Unter dem Ziel',
    legendLow: 'Geringe Produktion',
    menuData: 'Daten',
    exportBtn: 'Daten exportieren (Sicherung)',
    exportCsvBtn: 'CSV exportieren (Excel)',
    importBtn: 'Daten importieren',
    importWarning: 'Dies ersetzt die aktuellen Daten durch die der ausgewählten Datei. Fortfahren?',
    importSuccess: 'Daten erfolgreich importiert',
    importError: 'Ungültige Datei',
    dataExplain: 'Erstellen Sie gelegentlich eine Sicherung (z.B. auf Google Drive). Bei gelöschten Website-Daten oder Telefonwechsel ist dies die einzige Möglichkeit, Verlauf und Notizen wiederherzustellen.'
  }
};

const SHIFTS = [
  { id: 'manha', label: '05:00–14:00', startH: 5, endH: 14 },
  { id: 'tarde', label: '14:00–23:00', startH: 14, endH: 23 }
];
const SHIFT_LENGTH_H = 9;
const BREAK_H = 0.5;
const DAILY_GOAL = 18000;
const GOAL_LOW = 16000;
function goalColor(val) {
  if (val < GOAL_LOW) return 'var(--neg)';
  if (val < DAILY_GOAL) return 'var(--amber)';
  return 'var(--pos)';
}
function periodGoalColor(total, goal) {
  if (goal <= 0) return 'var(--ink)';
  const lowThresh = goal * (GOAL_LOW / DAILY_GOAL);
  if (total < lowThresh) return 'var(--neg)';
  if (total < goal) return 'var(--amber)';
  return 'var(--pos)';
}
const DAY_PREFIX = 'prod-';

function lang() { return localStorage.getItem('app-lang') || 'pt'; }
function setLang(l) {
  localStorage.setItem('app-lang', l);
  if (swReg && swReg.active) swReg.active.postMessage({ type: 'SET_LANG', lang: l });
}
function splashEnabled() { return localStorage.getItem('splash-enabled') !== 'off'; }
function setSplashEnabled(v) { localStorage.setItem('splash-enabled', v ? 'on' : 'off'); }
function t(key) { return STR[lang()][key]; }
